SELECT
    COUNT(*) AS PROYECTOS_FINALIZADOS
FROM
    PROYECTOS AS P
WHERE P.Fin < GETDATE()


-- ej 2.b

SELECT
    P.Descripcion
FROM
    PROYECTOS AS P
JOIN
    PROYECTO_ETAPA AS PE ON P.ID_PROYECTO = PE.ID_PROYECTO
JOIN
    ETAPAS AS E ON PE.ID_ETAPA = E.ID_ETAPA
WHERE
    E.Descripcion = 'Planificacion' AND PE.FIN_FECHA < '2022-7-1'

-- ej 2.c

SELECT 
    P.ID_PROYECTO,
    E.*
FROM
    PROYECTOS P
JOIN
    PROYECTO_EMPLEADO AS PE ON PE.ID_PROYECTO = P.ID_PROYECTO
JOIN
    EMPLEADO AS E ON E.ID_EMPLEDO = PE.ID_EMPLEADO
JOIN
    CATEGORIA AS C ON C.ID_CATEGORIA = E.ID_CATEGORIA
WHERE
    C.DESCRIPCION = 'Supervisor'


